---
output:
  md_document:
    variant: gfm

---
<p align="justify">    

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r setup, include = TRUE, echo = FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(dev = 'svg') # set output device to svg
```


```{r load and prep, include = TRUE, echo = FALSE, message = FALSE}
source("subscripts/load_and_clean_data.R")
library(tidyverse)
library(patchwork)
library(png)
library(ggtext)
library(tidyverse)
library(ggh4x)
library(ggimage)


ncd   = readPNG("raw/icons/NCD.png")
cd    = readPNG("raw/icons/CD.png")
wash  = readPNG("raw/icons/WASHOUT.png")
decaf = readPNG("raw/icons/DECAF.png")
caff  = readPNG("raw/icons/CAFF.png")
```

Fig. 1a: Cognitive effects of coffee. 
```{r, warning=FALSE, message = FALSE}
source("scripts/fig_1_behav_cog_health_data.R")
```

```{r plot_cog, warning=FALSE, message = FALSE, fig.width = 10, fig.height = 14}
(plot_cog_NCD | plot_cog_CD) + 
  plot_layout(guides = 'collect', widths = c(1,3)) & 
  theme(strip.text = element_text(size = 12))

```


```{r, plot_cog_craving, warning=FALSE, message = FALSE, fig.width = 10, fig.height = 8}
plot_cog_craving & 
  theme(strip.text = element_text(size = 12), strip.text.y.left = element_text(hjust = 1))
```

```{r fig_1_full, warning=FALSE, message=FALSE, fig.width=16, fig.height=9}
design_1 <- c("AAAAAAAAAAAABBCCCCCC
               AAAAAAAAAAAABBCCCCCC
               AAAAAAAAAAAABBCCCCCC
               DDDDDDDDDDDDBBCCCCCC
               DDDDDDDDDDDDBBCCCCCC
               DDDDDDDDDDDDBBCCCCCC")
(plot_spacer() + plot_cog_NCD + plot_cog_CD + plot_cog_craving) + plot_layout(design = design_1, guides = 'collect') & 
  theme(legend.position = 'left', 
        strip.text = element_text(size = 12), 
        strip.text.y.left = element_text(hjust = 1)
        )
```


Fig 2a Microbiome
```{r, warning=FALSE, message = FALSE}
source("scripts/fig_2_gi_microbiome_data.R")
```

```{r, plot_MB, warning=FALSE, message = FALSE, fig.width = 16, fig.height = 14}
(plot_mb_NCD |  plot_mb_CD) + 
  plot_layout(guides = 'collect', widths = c(1,8)) & 
  theme(strip.text = element_text(size = 12), 
        strip.text.y.left = element_text(hjust = 1)
        )

```


Fig 2b Metabolome
```{r, warning=FALSE, message = FALSE}
source("scripts/fig_2_gi_metabolome_data.R")
```


```{r plot_MT, fig.width=10, fig.height=10, message=FALSE, warning=FALSE}
(plot_mt_NCD | plot_mt_CD) + 
  plot_layout(guides = 'collect', widths = c(1,3)) & 
  theme(strip.text = element_text(size = 12), 
        strip.text.y.left = element_text(hjust = 1))
```

Fig 2b2 Urine Metabolome
```{r, warning=FALSE, message = FALSE}
source("scripts/fig_2_urine_metabolome_data_reclassed.R")
```


```{r, plot_met_urine, fig.width=12, fig.height=20, message=FALSE, warning=FALSE}
(plot_urmet_reclass_NCD  + plot_urmet_reclass_CD) + 
  plot_layout(widths = c(1,3), guides = 'collect') & 
  theme(strip.text = element_text(size = 12), 
        strip.text.y.left = element_text(hjust = 1))


#Sometimes bugs out, so alternatively:

# ggsave(plot = plot_urmet_NCD + guides(fill= "none"), width = 11,  height = 45, units = "cm", device = "svg", filename = "stats/urine_plot_a.svg")
# ggsave(plot = plot_urmet_CD + guides(fill= "none"), width = 8,  height = 45, units = "cm", device = "svg", filename = "stats/urine_plot_b.svg")


```

Fig 2bx Targeted faecal metabolomics
```{r, warning=FALSE, message = FALSE}
source("scripts/fig_2_faecal_metabolome_data_reclassed.R")
```


```{r, plot_met_fec, fig.width=10, fig.height=5, message=FALSE, warning=FALSE}
(plot_fecmet_reclass_NCD | plot_fecmet_reclass_CD) + 
  plot_layout(guides = 'collect', widths = c(1,3)) & 
  theme(strip.text = element_text(size = 12), 
        strip.text.y.left = element_text(hjust = 1))

```

Fig 2c Cytokines
```{r, warning=FALSE, message = FALSE}
source("scripts/fig_2_cytokine_data.R")
```


```{r, plot_cyt_stim, fig.width=10, fig.height=8, message=FALSE, warning=FALSE}
(plot_cyt_stim_NCD | plot_cyt_stim_CD) + 
  plot_layout(guides = 'collect', widths = c(1,3)) & 
  theme(strip.text = element_text(size = 12), 
        strip.text.y.left = element_text(hjust = 1))
```


```{r, plot_cyt_unstim, fig.width=10, fig.height=10, message=FALSE, warning=FALSE}
(plot_cyt_unstim_NCD | plot_cyt_unstim_CD) + 
  plot_layout(guides = 'collect', widths = c(1,3)) & 
  theme(strip.text = element_text(size = 12), 
        strip.text.y.left = element_text(hjust = 1))
```

```{r fig.width=12, fig.height=12, message=FALSE, warning=FALSE}
source("scripts/fig_final_integration.R")
```

```{r, plot_sankey_MB_MT_cog, fig.width=17, fig.height=10, message=FALSE, warning=FALSE}
fig_int
```

```{r fig.width=12, fig.height=12, message=FALSE, warning=FALSE}
source("scripts/fig_final_integration_MB_fecmet_cog.R")
```

```{r, plot_sankey_MB_fecmet_cog, fig.width=17, fig.height=10, message=FALSE, warning=FALSE}
fig_int_mb_fecmet_cog
```


```{r fig.width=12, fig.height=12, message=FALSE, warning=FALSE}
source("scripts/fig_final_integration_MB_urmet_cog.R")
```

```{r, plot_sankey_MB_urmet_cog, fig.width=17, fig.height=14, message=FALSE, warning=FALSE}

fig_int_mb_urmet_cog
```


#Microbiome in the middle
```{r fig.width=12, fig.height=12, message=FALSE, warning=FALSE}
source("scripts/fig_final_integration_fecmet_MB_behav.R")
```


```{r, plot_sankey_fecmet_MB_cog, fig.width=17, fig.height=10, message=FALSE, warning=FALSE}
fig_int_fecmet_MB_cog 
```


```{r fig.width=12, fig.height=12, message=FALSE, warning=FALSE}
# source("scripts/fig_final_integration_urmet_MB_behav.R")
```

```{r, fig_int_urmet_MB_cog, fig.width=17, fig.height=14, message=FALSE, warning=FALSE}

# fig_int_urmet_MB_cog
```



```{r generate_stats_tables, message=FALSE, warning=FALSE}
#source("scripts/generate_stats_tables.R")
```
